[meta]
version = "1.0.0"
description = "Security rules configuration"

[security]
block_patterns = [
    "*password*",
    "*_key",
    "*token*",
    "*secret*",
    "*credential*",
    "*api_key*",
    "*private*",
    "*auth*"
]

block_patterns_regex = [
    "localStorage\\.setItem\\(.*secret.*\\)",
    "sessionStorage\\.setItem\\(.*secret.*\\)",
    "console\\.log\\(.*password.*\\)",
    "document\\.cookie\\s*=",
    "eval\\(",
    "new\\s+Function\\("
]

allowed_domains = [
    "api.example.com",
    "*.trusted-domain.com"
]

[cors]
allowed_origins = ["https://*.example.com"]
allowed_methods = ["GET", "POST", "PUT", "DELETE"]
allow_credentials = true

[env.production]
security_mode = "strict"
block_patterns += [
    "console.log*",
    "debugger",
    "console.debug*"
] 